name: Run tests with memcheck
permissions:
  contents: read

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test_with_memchecks:
    name: Test with memchecks
    env:
      BUILD_TYPE: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install memcheck tool
        uses: gigabit-clowns/.github/.github/composites/memcheck/install-memtool@main
        id: install-memtool

      - name: Configure and build with CMake
        uses: threeal/cmake-action@v2
        with:
          source-dir: ${{ github.workspace }}
          build-dir: "${{ github.workspace }}/build"
          c-compiler: gcc
          cxx-compiler: g++
          options: |
            CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
            CMAKE_EXPORT_COMPILE_COMMANDS=ON
            XMIPP4_CORE_ENABLE_COVERAGE=ON
          run-build: true
          build-args: --config ${{ env.BUILD_TYPE }}

      - name: Run tests with memory check
        uses: gigabit-clowns/.github/.github/composites/run-ctest@main
        id: run-ctest
        with:
          check-memleaks: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Show memory leak logs (if exist)
        if: steps.run-ctest.outputs.exist-memleaks == 'true'
        uses: gigabit-clowns/.github/.github/composites/memcheck/show-memleaks@main
        with:
          test-numbers: ${{ steps.run-ctest.outputs.memleak-test-numbers }}
